on:
  push:
    tags:
      - "v*"
    paths:
      - "main.py"
      - "req.txt"
      - ".github/workflows/build.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: build binary file
        run: |

          pip install -r req.txt
          pip install pyinstaller
          pyinstaller --onefile --name pf main.py
          mkdir -p release
          mv dist/pf release

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: release/pf
          generate_release_notes: true
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}